#!/usr/bin/env python3
"""Deterministic R1-v2 artifact manifest generator.

Computes SHA-256 for each load-bearing artifact and binds:
  CANDIDATE_COMMIT, CANDIDATE_TREE, MODEL_CONDITION, REASONING_EFFORT,
  RUNTIME_POLICY, SESSION_ARITHMETIC, ARTIFACT_SHA256S, MANIFEST_SHA256,
  R1_V1_HISTORICAL_IDENTITIES

Usage:
  python bench/R1/generate_manifest.py                 # writes bench/R1/artifact-manifest-v2.json
  python bench/R1/generate_manifest.py --check         # verifies manifest matches current files + candidate
  python bench/R1/generate_manifest.py --print         # prints to stdout

All hashes are SHA-256 of raw file bytes (exact, including LF). No hand-invention.
"""

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

BENCH_DIR = Path(__file__).parent.resolve()
REPO_ROOT = BENCH_DIR.parent.parent.resolve()

# Load-bearing artifacts that must be pinned.
# Must match the set required by the hermit prompt §8.
ARTIFACTS = [
    "bench/R1/benchmark-spec-v2.json",
    "bench/R1/tasks-v2.json",
    "bench/R1/oracles-v2.json",
    "bench/R1/corpus-manifest-v2.json",
    "bench/R1/scorer.py",
    "bench/R1/validate.py",
    "bench/R1/test_scorer.py",
    "bench/R1/test_validate.py",
    "bench/R1/test_r1v2_statistical_design.py",
    "bench/R1/test_review_binding.py",
    "bench/R1/PREREGISTRATION-V2.md",
    "bench/R1/VARIANCE-PILOT-V2.md",
    "bench/R1/MAINTENANCE-V2.md",
    "bench/R1/generate_manifest.py",
    ".github/workflows/bench-r1-validation.yml",
    "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md",
    "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md",
    # Sealing procedure is not required to be in artifact list per §8, but is load-bearing for review.
    "docs/canonical/R1_V2_SEALING_PROCEDURE.md",
]

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())

def git_rev_parse(ref: str) -> str:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", ref],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        return out
    except Exception:
        return "UNKNOWN_NOT_A_GIT_REPO"

def load_spec():
    spec_path = BENCH_DIR / "benchmark-spec-v2.json"
    return json.loads(spec_path.read_text())

def build_manifest():
    spec = load_spec()
    candidate_commit = git_rev_parse("HEAD")
    candidate_tree = git_rev_parse("HEAD^{tree}")

    model_condition = spec.get("model_condition", {})
    reasoning_effort = model_condition.get("reasoning_effort", "medium")
    # Runtime policy as preregistered: fail-closed on drift, warn on floating alias not available.
    runtime_policy = "FAIL_CLOSED_ON_IDENTITY_DRIFT; MODEL_VERSION_PIN_STATUS=UNAVAILABLE_FLOATING_ALIAS_RECORD_PER_RUN"
    session_arithmetic = spec.get("session_arithmetic", {})
    hist = spec.get("historical_sealed_ids", {})

    artifacts = {}
    for rel in ARTIFACTS:
        p = REPO_ROOT / rel
        if not p.exists():
            # Missing file is a hard error — do not silently omit
            raise FileNotFoundError(f"Required artifact missing for manifest: {rel}")
        artifacts[rel] = sha256_file(p)

    # Manifest SHA256: deterministic hash of sorted artifact map + bindings (excluding itself).
    # This is the content hash that validation recomputes; it does not include candidate_commit
    # so that candidate staleness by one commit does not perturb the content hash.
    # We hash JSON serialization with sort_keys=True, separators=(',',':'), ensure_ascii=False.
    payload_for_hash = {
        "artifacts": artifacts,
        "model_condition": model_condition,
        "session_arithmetic": session_arithmetic,
        "historical_sealed_ids": hist,
    }
    canonical = json.dumps(payload_for_hash, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    manifest_sha256 = sha256_bytes(canonical)

    manifest = {
        "candidate_commit": candidate_commit,
        "candidate_tree": candidate_tree,
        "model_condition": model_condition,
        "reasoning_effort": reasoning_effort,
        "runtime_policy": runtime_policy,
        "session_arithmetic": session_arithmetic,
        "artifacts": artifacts,
        "manifest_sha256": manifest_sha256,
        "historical_sealed_ids": hist,
        "artifact_count": len(artifacts),
        "preregistration_version": spec.get("preregistration_version", "R1-PREREG-v2"),
        "notes": "Generated by bench/R1/generate_manifest.py — deterministic SHA-256 of file bytes. Do not hand-edit.",
    }
    return manifest

def main():
    parser = argparse.ArgumentParser(description="R1-v2 artifact manifest generator")
    parser.add_argument("--check", action="store_true", help="verify existing manifest matches current state")
    parser.add_argument("--print", action="store_true", dest="print_only", help="print to stdout instead of writing file")
    args = parser.parse_args()

    if args.check:
        manifest_path = BENCH_DIR / "artifact-manifest-v2.json"
        if not manifest_path.exists():
            print("FAIL: bench/R1/artifact-manifest-v2.json does not exist")
            return 1
        expected = build_manifest()
        actual = json.loads(manifest_path.read_text())
        errors = []
        # Allow candidate to be HEAD or HEAD~1 when only manifest changed (working vs review candidate distinction).
        # Strict equality is ideal, but one-behind is unavoidable due to manifest self-reference.
        head = expected["candidate_commit"]
        actual_candidate = actual.get("candidate_commit", "")
        if actual_candidate != head:
            head_parent = git_rev_parse("HEAD~1")
            if actual_candidate == head_parent:
                # Verify that artifact map is still correct and diff is only manifest
                try:
                    changed = subprocess.check_output(
                        ["git", "-C", str(REPO_ROOT), "diff", "--name-only", f"{actual_candidate}..HEAD"],
                        text=True,
                    ).strip().splitlines()
                    changed = [c.strip() for c in changed if c.strip()]
                except Exception:
                    changed = None
                # If changed files are not subset of {manifest}, treat as stale but allow with warning
                # Artifact map mismatch will be caught below, so we only warn here
                if changed is not None:
                    non_manifest = [c for c in changed if c != "bench/R1/artifact-manifest-v2.json"]
                    if non_manifest:
                        errors.append(f"candidate_commit mismatch: manifest {actual_candidate[:7]} vs HEAD {head[:7]} and non-manifest files changed: {non_manifest}")
                    else:
                        print(f"WARN: manifest candidate is parent {actual_candidate[:7]} vs HEAD {head[:7]} (only manifest changed) — allowing for self-reference")
                else:
                    errors.append(f"candidate_commit mismatch: manifest {actual_candidate} vs HEAD {head}")
            else:
                errors.append(f"candidate_commit mismatch: manifest {actual_candidate} vs HEAD {head}")
        # Tree check: allow parent tree similarly
        if actual.get("candidate_tree") != expected["candidate_tree"]:
            head_parent_tree = git_rev_parse("HEAD~1^{tree}")
            if actual.get("candidate_tree") != head_parent_tree:
                errors.append(f"candidate_tree mismatch: manifest {actual.get('candidate_tree')} vs HEAD {expected['candidate_tree']}")
            else:
                print(f"WARN: manifest candidate_tree is parent vs HEAD — allowing")
        if actual.get("manifest_sha256") != expected["manifest_sha256"]:
            errors.append(f"manifest_sha256 mismatch: manifest {actual.get('manifest_sha256')} vs computed {expected['manifest_sha256']}")
        if actual.get("artifacts") != expected["artifacts"]:
            for k in set(actual.get("artifacts", {})) | set(expected["artifacts"]):
                if actual.get("artifacts", {}).get(k) != expected["artifacts"].get(k):
                    errors.append(f"artifact {k}: manifest {actual.get('artifacts', {}).get(k)} vs current {expected['artifacts'].get(k)}")
        if errors:
            print("FAIL: manifest check errors:")
            for e in errors:
                print(f"  ERROR: {e}")
            return 1
        print(f"PASS: manifest matches HEAD {expected['candidate_commit'][:7]} tree {expected['candidate_tree'][:7]} artifacts {len(expected['artifacts'])} manifest_sha256 {expected['manifest_sha256'][:12]}")
        return 0

    manifest = build_manifest()
    out_text = json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    if args.print_only:
        print(out_text, end="")
        return 0
    out_path = BENCH_DIR / "artifact-manifest-v2.json"
    out_path.write_text(out_text)
    print(f"Wrote {out_path}")
    print(f"  candidate_commit={manifest['candidate_commit']}")
    print(f"  candidate_tree={manifest['candidate_tree']}")
    print(f"  artifacts={len(manifest['artifacts'])} manifest_sha256={manifest['manifest_sha256']}")
    for rel, h in sorted(manifest["artifacts"].items()):
        print(f"    {rel}: {h}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
