#!/usr/bin/env python3
"""Review-binding validation — fail closed when binding drifts.

Covers:
  candidate commit stale
  candidate tree stale
  artifact digest changes
  packet references wrong commit
  packet references wrong tree
  packet contains wrong task count
  packet contains wrong checkpoint count
  packet contains wrong session count
  packet contains wrong statistical formula
  packet claims R1-v2 empirical data before execution
  review status says PASS without independent evidence
  seal status says SEALED without prerequisites

Uses only deterministic file reads + git plumbing; no model execution.
"""

import hashlib
import json
import re
import subprocess
import unittest
from pathlib import Path

BENCH_DIR = Path(__file__).parent.resolve()
REPO_ROOT = BENCH_DIR.parent.parent.resolve()

def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def git_rev_parse(ref: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", ref],
            stderr=subprocess.DEVNULL, text=True
        ).strip()
    except Exception:
        return ""

def load_manifest():
    p = BENCH_DIR / "artifact-manifest-v2.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())

class TestReviewBinding(unittest.TestCase):
    def test_manifest_exists(self):
        self.assertTrue((BENCH_DIR / "artifact-manifest-v2.json").exists(),
                        "artifact-manifest-v2.json must exist (generated by generate_manifest.py)")

    def test_manifest_candidate_bound_to_head_or_parent(self):
        """Candidate commit in manifest must be HEAD or HEAD~1 if only manifest changed (allow one-behind)."""
        manifest = load_manifest()
        self.assertIsNotNone(manifest, "manifest required")
        head = git_rev_parse("HEAD")
        head_parent = git_rev_parse("HEAD~1") if head else ""
        candidate = manifest.get("candidate_commit", "")
        if candidate not in (head, head_parent):
            # Check if candidate is ancestor and diff only touches manifest
            try:
                changed = subprocess.check_output(
                    ["git", "-C", str(REPO_ROOT), "diff", "--name-only", f"{candidate}..HEAD"],
                    text=True
                ).strip().splitlines()
                changed = [c.strip() for c in changed if c.strip()]
            except Exception:
                changed = None
            # Fail with diagnostic
            self.fail(f"manifest candidate_commit {candidate[:7] if candidate else 'empty'} not HEAD {head[:7]} nor parent {head_parent[:7]}; changed files vs candidate: {changed}")

    def test_manifest_candidate_tree_matches_head_tree_or_parent(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        head_tree = git_rev_parse("HEAD^{tree}")
        head_parent_tree = git_rev_parse("HEAD~1^{tree}")
        candidate_tree = manifest.get("candidate_tree", "")
        self.assertIn(candidate_tree, (head_tree, head_parent_tree),
                        f"candidate_tree {candidate_tree[:7]} not HEAD tree {head_tree[:7]} nor parent {head_parent_tree[:7]}")

    def test_artifact_digests_match_current_files(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        artifacts = manifest.get("artifacts", {})
        # Must contain at least the required set
        required = [
            "bench/R1/benchmark-spec-v2.json",
            "bench/R1/tasks-v2.json",
            "bench/R1/oracles-v2.json",
            "bench/R1/corpus-manifest-v2.json",
            "bench/R1/scorer.py",
            "bench/R1/validate.py",
            "bench/R1/test_scorer.py",
            "bench/R1/test_validate.py",
            "bench/R1/PREREGISTRATION-V2.md",
            "bench/R1/VARIANCE-PILOT-V2.md",
            "bench/R1/MAINTENANCE-V2.md",
            ".github/workflows/bench-r1-validation.yml",
            "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md",
            "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md",
        ]
        for rel in required:
            self.assertIn(rel, artifacts, f"manifest missing required artifact {rel}")
            p = REPO_ROOT / rel
            self.assertTrue(p.exists(), f"artifact file missing {rel}")
            actual = sha256_file(p)
            self.assertEqual(actual, artifacts[rel], f"artifact digest drift for {rel}")

    def test_manifest_sha256_is_deterministic(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        # Recompute manifest_sha256 from artifacts + bindings (same logic as generator)
        spec = json.loads((BENCH_DIR / "benchmark-spec-v2.json").read_text())
        payload = {
            "artifacts": manifest.get("artifacts", {}),
            "model_condition": spec.get("model_condition", {}),
            "session_arithmetic": spec.get("session_arithmetic", {}),
            "historical_sealed_ids": spec.get("historical_sealed_ids", {}),
        }
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        expected = hashlib.sha256(canonical).hexdigest()
        self.assertEqual(manifest.get("manifest_sha256"), expected, "manifest_sha256 mismatch — artifact map or binding changed")

    def test_packet_references_not_stale_merge_identity(self):
        """Sealing procedure must not call ae155e5 a merge, must label PR34 correctly."""
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        # Must contain correct labeling
        self.assertIn("PR_34_HEAD=ec7a1eac5d6c45a8d4795b99bd1b41351dd72eef", sealing)
        self.assertIn("PR_34_MERGE=f8a0dd5e9b06e137a53157e99732d71d635f9a0f", sealing)
        self.assertIn("REVIEW_PACKET_COMMIT=ae155e5804922b41926163beacaf03b34f09b6cf", sealing)
        # Must not claim ae155e5 is PR #34 merge or latest main
        # Check that ae155e5 is described as review packet, not merge
        # Allow old erroneous line "Merge commit: `ae155e5` (latest main)" to be absent
        self.assertNotRegex(sealing, r"Merge commit:\s*`ae155e5`\s*\(latest main\)")

    def test_packet_task_counts_correct(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        # Both packets must state 30 tasks, 30 oracles, 96 evidence, 12 checkpoints, 972 sessions where relevant
        # Scientific packet §3 has timeline table
        self.assertRegex(sci, r"TOTAL_TASKS\s*=\s*30|TOTAL_TASKS.*30")
        self.assertIn("96", sci)  # corpus evidence count
        # Statistical packet must contain explicit 30 and 27-before-t14
        self.assertIn("30", stat)
        self.assertIn("27", stat)

    def test_packet_checkpoint_count(self):
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        # Must reference 12 checkpoints
        self.assertRegex(stat, r"12.*checkpoint|checkpoint.*12", re.IGNORECASE)
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        self.assertRegex(sci, r"12.*checkpoint|checkpoint.*12", re.IGNORECASE)

    def test_packet_session_count(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        for text in (sci, stat, sealing):
            # Session arithmetic must appear as 972 or 252+600+120
            self.assertTrue("972" in text or "252" in text, "session count 972 or 252 must appear")

    def test_packet_statistical_formula_correct(self):
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        # Must contain correct power formula and r_conf formula, not combinatoric
        self.assertIn("z_{1", stat)  # power formula
        self.assertIn("sqrt(psi", stat.lower().replace("ψ̂", "psi").replace("ψ", "psi"))
        self.assertIn("ceil( N_pairs / K_eligible", stat)
        # Must explicitly reject K(K-1)/2 as N_pairs
        self.assertIn("K_eligible", stat)
        # Should contain REJECTED combinatoric line
        self.assertRegex(stat, r"REJECTED.*K.*K.*1.*2|K_eligible.*K_eligible.*1.*2.*REJECTED", re.DOTALL | re.IGNORECASE)
        # Ensure not claiming N_pairs = K*(K-1)/2 as correct (without REJECTED)
        # We allow the rejected line, but must not have bare correct claim without rejection context
        # Check that packet does not contain a bare "N_pairs = K_eligible × (K_eligible - 1) / 2" outside rejected block
        # Simpler: ensure file contains "REJECTED" near that formula
        self.assertTrue("REJECTED" in stat and "K_eligible" in stat)

    def test_packet_does_not_claim_r1v2_empirical_data(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        for text in (sci, stat):
            # Must state NONE / NOT_EXECUTED for R1-v2 empirical
            self.assertRegex(text, r"R1_V2_EMPIRICAL_DATA\s*=\s*NONE|EMPIRICAL.*NONE", re.IGNORECASE)
            self.assertRegex(text, r"R1_V2_VARIANCE_PILOT\s*=\s*NOT_EXECUTED|VARIANCE_PILOT.*NOT_EXECUTED", re.IGNORECASE)
            # Must not claim "variance pilot data shows NO_DETECTABLE_DISCORDANCE" as R1-v2 data
            # Allow historical with qualifier, but not bare claim
            # If it contains "variance pilot data shows" without R1_V1 qualifier, fail
            if "variance pilot data shows" in text.lower():
                # Must also contain R1_V1 or HISTORICAL near that phrase
                self.assertRegex(text, r"R1_V1.*NO_DETECTABLE_DISCORDANCE|HISTORICAL.*NO_DETECTABLE", re.IGNORECASE | re.DOTALL)

    def test_review_status_not_pass_without_evidence(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        # Both packets status must be PENDING_INDEPENDENT_REVIEW at this stage
        self.assertIn("PENDING_INDEPENDENT_REVIEW", sci)
        self.assertIn("PENDING_INDEPENDENT_REVIEW", stat)
        # Must not contain PASS as overall packet status before independent review
        # Allow PASS inside prerequisites for machine validation, but not as R1_V2_SCIENTIFIC_REVIEW=PASS
        self.assertNotRegex(sci, r"R1_V2_SCIENTIFIC_REVIEW\s*=\s*PASS")
        self.assertNotRegex(stat, r"R1_V2_STATISTICAL_REVIEW\s*=\s*PASS")

    def test_seal_status_not_sealed_without_prerequisites(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        # Status must be SEALING_PREPARATION_PENDING (truthful), not PREPARATION_COMPLETE as current claim
        self.assertIn("SEALING_PREPARATION_PENDING", sealing)
        # Current status line must not be PREPARATION_COMPLETE; historical mention in explanation is allowed
        self.assertRegex(sealing, r"\*\*Status:\*\* `SEALING_PREPARATION_PENDING`")
        # Ensure no line declares **Status:** `PREPARATION_COMPLETE`
        self.assertNotRegex(sealing, r"\*\*Status:\*\* `PREPARATION_COMPLETE`")
        # Must not claim SEALED with a commit hash
        self.assertNotRegex(sealing, r"SEALED_CANDIDATE=[^\s]*[0-9a-f]{7,}")

    def test_sealing_procedure_no_duplicate_v2(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        # The active field name must not be R1_V2_V2_CONFIRMATORY_EXECUTION; historical mention in comment is allowed
        # Check that no active prerequisite line uses the duplicate
        # Allow a line that says "prior draft had R1_V2_V2_CONFIRMATORY_EXECUTION" as explanatory, but not as the field name
        lines = [l for l in sealing.splitlines() if "R1_V2_V2_CONFIRMATORY" in l]
        for line in lines:
            # Any remaining occurrence must be in a comment explaining the correction
            self.assertIn("prior draft had", line.lower())

    def test_candidate_states_defined(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        for state in ["WORKING_CANDIDATE", "REVIEW_CANDIDATE", "SEALED_CANDIDATE", "EXECUTION_CANDIDATE"]:
            self.assertIn(state, sealing)

    def test_stale_review_rule_present(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertIn("AFFECTED_REVIEW=STALE", sealing)
        self.assertIn("RE_REVIEW_REQUIRED=YES", sealing)
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        self.assertIn("AFFECTED_REVIEW=STALE", stat)
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        self.assertIn("AFFECTED_REVIEW=STALE", sci)

    def test_no_ceiling_second_invention(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        # Both must preserve canonical routing and not invent SECOND_CEILING=THESIS_NOT_SUPPORTED
        for text in (sci, sealing):
            self.assertRegex(text, r"NOT_THESIS_SUPPORT|NOT_THESIS_FALSIFICATION|NO_SILENT_CONTINUATION", re.IGNORECASE)
            # If SECOND_CEILING appears, it must be marked NOT_PREREGISTERED
            if "SECOND_CEILING" in text:
                self.assertIn("NOT_PREREGISTERED", text)

    def test_review_binding_packet_commit_matches(self):
        # Packet's REVIEW_PACKET_COMMIT should equal manifest historical? Not required, but should be consistent
        # Check that sealing procedure's REVIEW_PACKET_COMMIT is ae155e5 and not called merge
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertIn("ae155e5804922b41926163beacaf03b34f09b6cf", sealing)


if __name__ == "__main__":
    unittest.main(verbosity=2)
