#!/usr/bin/env python3
"""Review-binding validation — fail closed when binding drifts.

Covers:
  candidate commit/tree binding
  artifact digest and manifest drift
  packet identities/counts/formulas
  empirical-data and review-status boundaries
  seal-state prerequisites
  stale-review law
  self-reference-safe review-candidate binding

Uses only deterministic file reads + git plumbing; no model execution.
"""

import hashlib
import json
import re
import subprocess
import unittest
from pathlib import Path

BENCH_DIR = Path(__file__).parent.resolve()
REPO_ROOT = BENCH_DIR.parent.parent.resolve()


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git_rev_parse(ref: str) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", ref],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return ""


def load_manifest():
    path = BENCH_DIR / "artifact-manifest-v2.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


class TestReviewBinding(unittest.TestCase):
    def test_manifest_exists(self):
        self.assertTrue(
            (BENCH_DIR / "artifact-manifest-v2.json").exists(),
            "artifact-manifest-v2.json must exist (generated by generate_manifest.py)",
        )

    def test_manifest_candidate_bound_to_head_or_parent(self):
        """Candidate commit may be HEAD or an ancestor only when current artifact bytes still match."""
        manifest = load_manifest()
        self.assertIsNotNone(manifest, "manifest required")
        head = git_rev_parse("HEAD")
        candidate = manifest.get("candidate_commit", "")
        if candidate == head:
            return
        head_parent = git_rev_parse("HEAD~1") if head else ""
        if candidate == head_parent:
            return
        try:
            is_ancestor = (
                subprocess.call(
                    ["git", "-C", str(REPO_ROOT), "merge-base", "--is-ancestor", candidate, head],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                == 0
            )
        except Exception:
            is_ancestor = False
        if is_ancestor:
            return
        self.fail(
            f"manifest candidate_commit {candidate[:7] if candidate else 'empty'} "
            f"is not HEAD {head[:7]} or an ancestor"
        )

    def test_manifest_candidate_tree_matches_candidate_commit(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        candidate = manifest.get("candidate_commit", "")
        candidate_tree = manifest.get("candidate_tree", "")
        expected_tree = git_rev_parse(f"{candidate}^{{tree}}") if candidate else ""
        self.assertTrue(candidate and expected_tree, "manifest candidate commit must resolve")
        self.assertEqual(
            candidate_tree,
            expected_tree,
            "manifest candidate_tree must be the exact tree of manifest candidate_commit",
        )

    def test_artifact_digests_match_current_files(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        artifacts = manifest.get("artifacts", {})
        required = [
            "bench/R1/benchmark-spec-v2.json",
            "bench/R1/tasks-v2.json",
            "bench/R1/oracles-v2.json",
            "bench/R1/corpus-manifest-v2.json",
            "bench/R1/scorer.py",
            "bench/R1/validate.py",
            "bench/R1/test_scorer.py",
            "bench/R1/test_validate.py",
            "bench/R1/test_r1v2_statistical_design.py",
            "bench/R1/test_review_binding.py",
            "bench/R1/PREREGISTRATION-V2.md",
            "bench/R1/VARIANCE-PILOT-V2.md",
            "bench/R1/MAINTENANCE-V2.md",
            "bench/R1/generate_manifest.py",
            ".github/workflows/bench-r1-validation.yml",
            "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md",
            "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md",
            "docs/canonical/R1_V2_SEALING_PROCEDURE.md",
        ]
        self.assertEqual(len(required), 18)
        for rel in required:
            self.assertIn(rel, artifacts, f"manifest missing required artifact {rel}")
            path = REPO_ROOT / rel
            self.assertTrue(path.exists(), f"artifact file missing {rel}")
            self.assertEqual(
                sha256_file(path),
                artifacts[rel],
                f"artifact digest drift for {rel}",
            )

    def test_manifest_sha256_is_deterministic(self):
        manifest = load_manifest()
        self.assertIsNotNone(manifest)
        spec = json.loads((BENCH_DIR / "benchmark-spec-v2.json").read_text())
        payload = {
            "artifacts": manifest.get("artifacts", {}),
            "model_condition": spec.get("model_condition", {}),
            "session_arithmetic": spec.get("session_arithmetic", {}),
            "historical_sealed_ids": spec.get("historical_sealed_ids", {}),
        }
        canonical = json.dumps(
            payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
        ).encode("utf-8")
        expected = hashlib.sha256(canonical).hexdigest()
        self.assertEqual(
            manifest.get("manifest_sha256"),
            expected,
            "manifest_sha256 mismatch — artifact map or binding changed",
        )

    def test_sealing_procedure_does_not_embed_historical_live_main_binding(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertNotIn("CURRENT_MAIN_COMMIT=", sealing)
        self.assertNotIn("CURRENT_MAIN_TREE=", sealing)
        self.assertNotRegex(
            sealing,
            re.compile(r"latest main[^\n]*[0-9a-f]{7,}", re.IGNORECASE),
        )
        self.assertIn("The frozen review identity must be obtained mechanically from Git", sealing)

    def test_packet_task_counts_correct(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        self.assertRegex(sci, r"TOTAL_TASKS\s*=\s*30|TOTAL_TASKS.*30")
        self.assertIn("96", sci)
        self.assertIn("30", stat)
        self.assertIn("27", stat)

    def test_packet_checkpoint_count(self):
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        self.assertRegex(stat.lower(), r"12.*checkpoint|checkpoint.*12")
        self.assertRegex(sci.lower(), r"12.*checkpoint|checkpoint.*12")

    def test_packet_session_count(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        for text in (sci, stat, sealing):
            self.assertTrue(
                "972" in text or "252" in text,
                "session count 972 or 252 must appear",
            )

    def test_packet_statistical_formula_correct(self):
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        self.assertIn("z_{1", stat)
        normalized = stat.lower().replace("ψ̂", "psi").replace("ψ", "psi")
        self.assertIn("sqrt(psi", normalized)
        self.assertIn("ceil( N_pairs / K_eligible", stat)
        self.assertIn("K_eligible", stat)
        self.assertRegex(
            stat,
            re.compile(
                r"REJECTED.*K.*K.*1.*2|K_eligible.*K_eligible.*1.*2.*REJECTED",
                re.DOTALL | re.IGNORECASE,
            ),
        )
        self.assertIn("REJECTED", stat)

    def test_packet_does_not_claim_r1v2_empirical_data(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        for text in (sci, stat):
            self.assertRegex(
                text,
                re.compile(r"R1_V2_EMPIRICAL_DATA\s*=\s*NONE|EMPIRICAL.*NONE", re.IGNORECASE),
            )
            self.assertRegex(
                text,
                re.compile(
                    r"R1_V2_VARIANCE_PILOT\s*=\s*NOT_EXECUTED|VARIANCE_PILOT.*NOT_EXECUTED",
                    re.IGNORECASE,
                ),
            )
            if "variance pilot data shows" in text.lower():
                self.assertRegex(
                    text,
                    re.compile(
                        r"R1_V1.*NO_DETECTABLE_DISCORDANCE|HISTORICAL.*NO_DETECTABLE",
                        re.IGNORECASE | re.DOTALL,
                    ),
                )

    def test_review_status_not_pass_without_evidence(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        # Founder decision 2026-09-08 supersedes mandatory human PENDING; packets now mark SUPERSEDED + INTERNALLY_QUALIFIED
        self.assertIn("SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION_2026-09-08", sci)
        self.assertIn("SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION_2026-09-08", stat)
        self.assertIn("HUMAN_REVIEW_OPTIONAL", sci)
        self.assertIn("HUMAN_REVIEW_OPTIONAL", stat)
        self.assertIn("INTERNALLY_QUALIFIED", sci)
        self.assertIn("INTERNALLY_QUALIFIED", stat)
        self.assertNotRegex(sci, r"R1_V2_SCIENTIFIC_REVIEW\s*=\s*PASS")
        self.assertNotRegex(stat, r"R1_V2_STATISTICAL_REVIEW\s*=\s*PASS")
        # Ensure no fake human PASS is claimed
        self.assertIn("INDEPENDENT_HUMAN_REVIEW_REQUIREMENT=SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION", sci)
        self.assertIn("INDEPENDENT_HUMAN_REVIEW_REQUIREMENT=SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION", stat)

    def test_seal_status_not_sealed_without_prerequisites(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertIn("SEALING_PREPARATION_PENDING", sealing)
        self.assertRegex(sealing, r"\*\*Status:\*\* `SEALING_PREPARATION_PENDING`")
        self.assertNotRegex(sealing, r"\*\*Status:\*\* `PREPARATION_COMPLETE`")
        self.assertNotRegex(sealing, r"SEALED_CANDIDATE=[^\s]*[0-9a-f]{7,}")

    def test_sealing_procedure_no_duplicate_v2(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        lines = [line for line in sealing.splitlines() if "R1_V2_V2_CONFIRMATORY" in line]
        for line in lines:
            self.assertIn("prior draft had", line.lower())

    def test_candidate_states_defined(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        for state in [
            "WORKING_CANDIDATE",
            "REVIEW_CANDIDATE",
            "SEALED_CANDIDATE",
            "EXECUTION_CANDIDATE",
        ]:
            self.assertIn(state, sealing)

    def test_sealing_procedure_uses_external_exact_candidate_binding(self):
        """Prevent stale self-pins such as REVIEW_CANDIDATE=NOT_YET_FROZEN or historical latest-main SHAs."""
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertIn("REVIEW_CANDIDATE_BINDING_SOURCE", sealing)
        self.assertIn("specs/CURRENT.md", sealing)
        # Founder decision 2026-09-08: active issue binding superseded; deterministic manifest now gates
        self.assertIn("bench/R1/artifact-manifest-v2.json", sealing)
        self.assertIn("SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION", sealing)
        self.assertIn("no self-reference", sealing.lower())
        self.assertNotIn("REVIEW_CANDIDATE=NOT_YET_FROZEN", sealing)
        self.assertNotIn("CURRENT_MAIN_COMMIT=0d206cac9a6e5ebfe3d47401aa1f081a587af60f", sealing)
        self.assertNotIn("CURRENT_MAIN_TREE=6943decf800574906b76b0abd7dc5a3460cef072", sealing)

    def test_stale_review_rule_present(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        stat = (REPO_ROOT / "docs/canonical/R1_V2_STATISTICAL_REVIEW_PACKET.md").read_text()
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        self.assertIn("AFFECTED_REVIEW=STALE", sealing)
        self.assertIn("RE_REVIEW_REQUIRED=YES", sealing)
        self.assertIn("AFFECTED_REVIEW=STALE", stat)
        self.assertIn("AFFECTED_REVIEW=STALE", sci)

    def test_no_ceiling_second_invention(self):
        sci = (REPO_ROOT / "docs/canonical/R1_V2_SCIENTIFIC_REVIEW_PACKET.md").read_text()
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        for text in (sci, sealing):
            self.assertRegex(
                text,
                re.compile(
                    r"NOT_THESIS_SUPPORT|NOT_THESIS_FALSIFICATION|NO_SILENT_CONTINUATION",
                    re.IGNORECASE,
                ),
            )
            if "SECOND_CEILING" in text:
                self.assertIn("NOT_PREREGISTERED", text)

    def test_review_binding_source_contract_is_explicit(self):
        sealing = (REPO_ROOT / "docs/canonical/R1_V2_SEALING_PROCEDURE.md").read_text()
        self.assertIn("REVIEW_CANDIDATE_BINDING_SOURCE", sealing)
        self.assertIn("specs/CURRENT.md", sealing)
        # After founder supersession, binding is via CURRENT + deterministic manifest, not mandatory issue #43/#44
        self.assertIn("bench/R1/artifact-manifest-v2.json", sealing)
        self.assertIn("MANIFEST_CANDIDATE_COMMIT", sealing)
        self.assertIn("MANIFEST_CANDIDATE_TREE", sealing)
        self.assertIn("SUPERSEDED_BY_FOUNDER_GOVERNANCE_DECISION", sealing)


if __name__ == "__main__":
    unittest.main(verbosity=2)
